CRITICAL - 2021-02-19 00:25:45 --> Unable to connect to the database.
#0 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Models\LoginModel.php(61): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(93): Myth\Auth\Models\LoginModel->getRememberToken('7111cc115c62b8f...')
#4 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(46): Myth\Auth\Authentication\LocalAuthenticator->check()
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->login()
#6 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#7 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-02-19 00:25:47 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\korlantas\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\korlantas\app\Views\errors\html\error_exception.php(100): print_r(Object(Myth\Auth\Controllers\AuthController), true)
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-02-19 00:27:57 --> Unable to connect to the database.
#0 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Models\LoginModel.php(61): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(93): Myth\Auth\Models\LoginModel->getRememberToken('7111cc115c62b8f...')
#4 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(46): Myth\Auth\Authentication\LocalAuthenticator->check()
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->login()
#6 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#7 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-02-19 00:27:57 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\korlantas\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\korlantas\app\Views\errors\html\error_exception.php(100): print_r(Object(Myth\Auth\Controllers\AuthController), true)
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-02-19 00:39:52 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Views\_message_block.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#3 C:\xampp\htdocs\korlantas\app\Views\auth\register.php(40): view('Myth\\Auth\\Views...')
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\auth...', Array, true)
#6 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(431): view('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(147): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array, Array, Array)
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->register()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2021-02-19 00:42:24 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\korlantas\app\Views\admin\_partials\_message_block.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('admin\\_partials...', Array, true)
#3 C:\xampp\htdocs\korlantas\app\Views\auth\register.php(40): view('admin\\_partials...')
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\auth...', Array, true)
#6 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(431): view('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(147): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array, Array, Array)
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->register()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2021-02-19 00:46:38 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\korlantas\app\Views\admin\_partials\_message_block.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('admin\\_partials...', Array, true)
#3 C:\xampp\htdocs\korlantas\app\Views\auth\register.php(40): view('admin\\_partials...')
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\auth...', Array, true)
#6 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(431): view('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(147): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array, Array, Array)
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->register()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2021-02-19 00:47:35 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\korlantas\app\Views\admin\_partials\_message_block.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('admin\\_partials...', Array, true)
#3 C:\xampp\htdocs\korlantas\app\Views\auth\register.php(40): view('admin\\_partials...')
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\auth...', Array, true)
#6 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(431): view('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(147): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array, Array, Array)
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->register()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2021-02-19 00:48:40 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Views\_message_block.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#3 C:\xampp\htdocs\korlantas\app\Views\auth\register.php(40): view('Myth\\Auth\\Views...')
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\auth...', Array, true)
#6 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(431): view('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(147): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array, Array, Array)
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->register()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2021-02-19 00:54:48 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Views\_message_block.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#3 C:\xampp\htdocs\korlantas\app\Views\auth\register.php(40): view('Myth\\Auth\\Views...')
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\auth...', Array, true)
#6 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(431): view('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(147): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array, Array, Array)
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->register()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2021-02-19 01:01:46 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Views\_message_block.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#3 C:\xampp\htdocs\korlantas\app\Views\auth\register.php(40): view('Myth\\Auth\\Views...')
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\auth...', Array, true)
#6 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(431): view('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(147): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array, Array, Array)
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->register()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2021-02-19 01:05:03 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Views\_message_block.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#3 C:\xampp\htdocs\korlantas\app\Views\auth\register.php(40): view('Myth\\Auth\\Views...')
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\auth...', Array, true)
#6 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(431): view('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(147): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array, Array, Array)
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->register()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2021-02-19 01:07:03 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Views\_message_block.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#3 C:\xampp\htdocs\korlantas\app\Views\auth\register.php(40): view('Myth\\Auth\\Views...')
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\auth...', Array, true)
#6 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(431): view('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(147): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array, Array, Array)
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->register()
#9 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2021-02-19 01:33:52 --> Undefined variable: sent
#0 C:\xampp\htdocs\korlantas\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(199): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 199, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->attemptRegister()
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#3 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-02-19 02:02:54 --> Declaration of App\Models\Upload::insert($data) should be compatible with CodeIgniter\Model::insert($data = NULL, bool $returnID = true)
#0 C:\xampp\htdocs\korlantas\app\Models\Upload.php(5): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Declaration of ...', 'C:\\xampp\\htdocs...', 5, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(365): require_once('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Uplo...')
#4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Uplo...')
#5 C:\xampp\htdocs\korlantas\app\Controllers\Dashboard.php(21): spl_autoload_call('App\\Models\\Uplo...')
#6 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Dashboard->store()
#7 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-02-19 02:10:02 --> Declaration of App\Models\Upload::insert($data) should be compatible with CodeIgniter\Model::insert($data = NULL, bool $returnID = true)
#0 C:\xampp\htdocs\korlantas\app\Models\Upload.php(5): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Declaration of ...', 'C:\\xampp\\htdocs...', 5, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(365): require_once('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Uplo...')
#4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Uplo...')
#5 C:\xampp\htdocs\korlantas\app\Controllers\Dashboard.php(21): spl_autoload_call('App\\Models\\Uplo...')
#6 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Dashboard->store()
#7 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-02-19 02:11:50 --> Class 'App\Controllers\UploadModel' not found
#0 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Dashboard->store()
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-02-19 02:12:17 --> Class 'App\Controllers\UploadModel' not found
#0 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Dashboard->store()
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-02-19 02:12:39 --> Declaration of App\Models\UploadModel::insert($data) should be compatible with CodeIgniter\Model::insert($data = NULL, bool $returnID = true)
#0 C:\xampp\htdocs\korlantas\app\Models\UploadModel.php(5): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Declaration of ...', 'C:\\xampp\\htdocs...', 5, Array)
#1 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(365): require_once('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Uplo...')
#4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Uplo...')
#5 C:\xampp\htdocs\korlantas\app\Controllers\Dashboard.php(21): spl_autoload_call('App\\Models\\Uplo...')
#6 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Dashboard->store()
#7 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#8 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\korlantas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\korlantas\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#11 {main}
